language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

cache: cargo

matrix:
  fast_finish: true

script:
  - cargo check --verbose --examples
  - cargo check --verbose --no-default-features
  - cargo check --verbose --features="embedded_images"
  - cargo test --verbose

notifications:
  email: false
