[package]
name = "shared"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
moonlight.workspace = true
rand = "*"

[features]
frontend = ["moonlight/frontend"]
backend = ["moonlight/backend"]
